### ISSUE TITLE
フロントエンドCI>Self-hosted runnerでキャッシュ無効化

### ISSUE THREAD

**Issue by ryosuke-horie** [ryosuke-horie/saifuu#28]
## 問題

フロントエンドCIでSelf-hosted runnerを使用しているにも関わらず、Node.jsキャッシュが有効になっている。

**現在の設定（.github/workflows/frontend-ci.yml）:**
```yaml
- name: Setup Node.js
  uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
  with:
    node-version: '22'
    cache: 'npm'  # ← これを削除する必要がある
    cache-dependency-path: frontend/package-lock.json  # ← これも削除
```

## 根拠

CLAUDE.mdの「セルフホストランナー運用ルール」に明記されている制約：

> ### 重要な制約
> - **キャッシュ無効**: セルフホストランナーのマシン性能の都合によりNode.js キャッシュは使用しない
> - **パフォーマンス優先**: キャッシュによる遅延を避けるため、毎回クリーンインストールを実行

## APIの実装との整合性

APIのCI設定では既に正しく実装済み：
```yaml
- name: Setup Node.js
  uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
  with:
    node-version: '22'
    # セルフホストランナーの制約によりキャッシュは無効
    # cache: 'npm'
    # cache-dependency-path: api/package-lock.json
```

## 修正内容

フロントエンドCIでもキャッシュ設定を削除し、APIと同様の設定に統一する：

```yaml
- name: Setup Node.js
  uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
  with:
    node-version: '22'
    # セルフホストランナーの制約によりキャッシュは無効
    # cache: 'npm'
    # cache-dependency-path: frontend/package-lock.json
```

## 期待される効果

- Self-hosted runnerの性能制約に適合
- パフォーマンス向上（キャッシュ遅延回避）
- API・フロントエンド間でのCI設定統一
- 複数ランナー同時実行時の競合回避
